### ISSUE TITLE
Turn on Zenodo for automatic code DOIs?

### ISSUE THREAD

**Issue by davidlmobley** [drugdata/D3R_GC2_evaluation#2]
It would be good to make evaluation code versioned and cite-able. You can use the "release" functionality for versioning, but to make it easy to cite and access specific versions, I suggest turning on (free) Zenodo, which automatically assigns each new release a permanent, cite-able DOI and allows for easy retrieval of them.

**Comment by shuail** [comment]
We have turned on the zenodo github link and will cut a release soon which should create a DOI for us.

**Comment by shuail** [comment]
We pushed the first release and create a citable DOI through Zenodo. The DOI link is doi.org/10.5281/zenodo.556574. We also update the README file to add a Zenodo badge. Thanks for the advices!
